package client.conveyor;

public enum RequestConstants {
    STATUS,
    REASON,
    SUCCESS,
    FAILED,
    UUID_REGISTRATION,
    INIT_GAME_SESSION,
    GAME_SESSION_NAME,
    CONNECT_TO_GAME_SESSION,
    QUIT_FROM_GAME_SESSION,
    GET_DATA_FROM_GAME_SESSION,
    SET_DATA_TO_GAME_SESSION,
    ERROR_REQUEST,
    COULDNT_FIND_YOUR_ID,
    UNSUPPORTED_REQUEST_FORMAT,
    CARDS_IN_TOWER,
    CARDS_AT_PLAYER,
    BOTTOM_CARD,
    CURRENT_PLAYER,
    PLAYERS_IN_SESSION,
    TURN_CARD_NUM,
    TURN_CARD_SUIT,
    TURN_END,
    TOTAL_CARDS_NUMBER,
    ALL_PLAYERS_CARDS,
    SET_GAME_START,
    IS_GAME_PLAYING;

    private RequestConstants() {

    }
}
