package server.commander;

public enum RequestConstants {
    STATUS,
    REASON,
    SUCCESS,
    FAILED,
    UUID_REGISTRATION,
    INIT_GAME_SESSION,
    CONNECT_TO_GAME_SESSION,
    QUIT_FROM_GAME_SESSION,
    GET_DATA_FROM_GAME_SESSION,
    SET_DATA_TO_GAME_SESSION,
    ERROR_REQUEST,
    COULDNT_FIND_YOUR_ID,
    UNSUPPORTED_REQUEST_FORMAT,
    CARDS_IN_TOWER,
    CARDS_AT_PLAYER,
    BOTTOM_CARD,
    CURRENT_PLAYER;

    private RequestConstants() {

    }
}
